### ISSUE TITLE
ctrl + shift + R doesn't work

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [p-/eclipse-keybindings#4]
I have been trying <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>R</kbd> as stated in the docs but it simply doesn't work.

**Comment by p-** [comment]
Hi there
Could you please tell me the Atom version and the system your on (Mac, Linux, Win)?
Also could you first press <kbd>Ctrl</kbd> + <kbd>.</kbd> and then <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> and tell me which (if any) plugin is responding (it is displayed on a bar below the editor). Thanks!

**Comment by FagnerMartinsBrack** [comment]
Of course:

<kbd>Ctrl</kbd> + <kbd>.</kbd> doesn't do anything.
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> doesn't do anything.
<kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> works commenting the selected line.

Mac OS X El Capitan Version 10.11.1 (15B42)
Atom 1.6.1
eclipse-keybindings 0.9.0

**Comment by p-** [comment]
Hi, thanks for the info.
Ah, you're using a Mac!
I stated 'Mac users: press ⌘ instead of Ctrl (same as in Eclipse on Mac).'
Might not be that obvious. So <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> and <kbd>Cmd</kbd> + <kbd>.</kbd> should work.

It seems to be the default behavior of Eclipse on Mac that <kbd>Cmd (⌘)</kbd> is used for most commands instead of <kbd>Ctrl</kbd>. Do you have a different experience?

**Comment by FagnerMartinsBrack** [comment]
Oh, the docs are misleading then. Using <kbd>Cmd (⌘)</kbd> it works :)
What about upgrading the docs to account for Mac users too? :)

**Comment by ih4t3youall** [comment]
i know this is not the place but thank you for this keybinding it work perfectly and i love it
